name: lite_agent_core_server
description: Dart版本Lite Agent Core的HTTP Server封装
version: 0.1.0
repository: https://gitlab.litevar.com:90/litevar/jan/lite_agent_core_dart_server

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^2.0.0
  logging: ^1.2.0
  uuid: ^4.4.0
  json_annotation: ^4.9.0
  lite_agent_core_dart:
    path: /Users/jan/Project/lite_agent_core_dart

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
  dio: ^5.4.3+1
  dotenv: ^4.2.0
